name: Build Experimental

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
      - "src/**"
      - "include/**"
      - "generated_src/**"
      - "generated_include/**"
      - "Dependencies/**"

jobs:
  Build:
    permissions: write-all
    runs-on: windows-2022

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
          ssh-key: ${{ secrets.UEPSEUDO_SSH_KEY }}

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@v1

      - name: Setup Ninja
        uses: seanmiddleditch/gha-setup-ninja@v3
        
      - name: Build
        run: |
          cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=Release
          cmake --build build

      - name: Package
        run: python tools/buildscripts/build.py package

      - name: Update Experimental release
        uses: ncipollo/release-action@v1.12.0
        with:
          name: "UE4SS Experimental Release"
          tag: experimental
          artifacts: |
              release/UE4SS_Standard_v*.zip
              release/UE4SS_Xinput_v*.zip
              release/zDEV-UE4SS_Standard_v*.zip
              release/zDEV-UE4SS_Xinput_v*.zip
              release/zCustomGameConfigs.zip
              release/zMapGenBP.zip
          bodyFile: release/release_notes.md
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}
